platform :ios, '13.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

project 'app', 'Debug(Development)' => :debug, 'Debug(Staging)' => :debug, 'Debug(Production)' => :debug, 'Release(Development)' => :release, 'Release(Staging)' => :release, 'Release(Production)' => :release

permissions_path = '../node_modules/react-native-permissions/ios'

target 'app' do
  pod 'react-native-ffmpeg/full-gpl', :podspec => '../node_modules/react-native-ffmpeg/react-native-ffmpeg.podspec'

	config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )

  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"

  post_install do |installer|
    react_native_post_install(installer)
  end

end
