export const IOS_APP_ID = '1551946709';
export const SUBSCRIPTION_ID = 'com.onedollarxclub.sub.monthly';
export const APPS_FLYER_DEV_KEY = '7qFXDVUVSmhxm7DN6DYK54';

export const ASYNC_STORAGE_KEYS = {
  INITIAL_TOS_AGREE_RECORDING_ID: 'INITIAL_TOS_AGREE_RECORDING_ID',
  TRACKING_ENABLED: 'TRACKING_ENABLED',
  LATEST_REMOTE_MESSAGE: 'LATEST_REMOTE_MESSAGE',
  CHAT_TOKEN: 'CHAT_TOKEN',
  SAVED_ATTACHMENTS_BASE: 'odxc-saved-attachments-',
  CACHED_PURCHASE: 'CACHED_PURCHASE',
  HAS_REQUESTED_PN_PERMISSION: 'HAS_REQUESTED_PN_PERMISSION',
  HAS_REQUESTED_GPS_PERMISSION: 'HAS_REQUESTED_GPS_PERMISSION',
};

export const STORAGE_VALUE_TRUE = 'TRUE';
export const STORAGE_VALUE_FALSE = 'FALSE';
